name: Docker

on:
  push:
    branches:
      - master
  pull_request:
  # 定期更新をやる(毎週月曜日)
  schedule:
    - cron:  '0 0 * * 1'

env:
  IMAGE_NAME: php
jobs:
  push:
    strategy:
      matrix:
        images:
          - "7.2/alpine/fpm"
          - "7.2/debian/fpm"
          - "7.3/alpine/fpm"
          - "7.3/debian/fpm"
          - "7.4/alpine/fpm"
          - "7.4/debian/fpm"

    runs-on: ubuntu-latest

    steps:
      - name: cancel old workflow
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: set IMAGE VERSION
        run: echo ::set-env name=IMAGE_VERSION::$(echo "${{ matrix.images }}" | sed -e 's/debian\///g' -e 's/\//-/g')

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          dockerfile: ${{ matrix.images }}/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: fagai/${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_VERSION }}
          build_args: BUILDKIT_INLINE_CACHE=1
          cache_froms: docker.io/fagai/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

      - name: Push to GitHub Container Registory
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          dockerfile: ${{ matrix.images }}/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: fagai/${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_VERSION }}

  push-phalcon:
    needs: push
    strategy:
      fail-fast: false
      matrix:
        images:
          - "7.2/alpine/phalcon-fpm"
          - "7.2/debian/phalcon-fpm"
          - "7.3/alpine/phalcon-fpm"
          - "7.3/debian/phalcon-fpm"
          - "7.4/alpine/phalcon4-fpm"
          - "7.4/debian/phalcon4-fpm"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: set IMAGE VERSION
        run: echo ::set-env name=IMAGE_VERSION::$(echo "${{ matrix.images }}" | sed -e 's/debian\///g' -e 's/\//-/g')

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          dockerfile: ${{ matrix.images }}/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: fagai/${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_VERSION }}
          build_args: BUILDKIT_INLINE_CACHE=1
          cache_froms: docker.io/fagai/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

      - name: Push to GitHub Container Registory
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          dockerfile: ${{ matrix.images }}/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: fagai/${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_VERSION }}