name: Docker

on:
  push:
    branches:
      - master
  pull_request:
  # 定期更新をやる(毎週月曜日)
  schedule:
    - cron:  '0 0 * * 1'

env:
  IMAGE_NAME: php
jobs:
  push:
    strategy:
      matrix:
        images:
          - "7.2/alpine/fpm"
          - "7.2/debian/fpm"
          - "7.3/alpine/fpm"
          - "7.3/debian/fpm"
          - "7.4/alpine/fpm"
          - "7.4/debian/fpm"

    runs-on: ubuntu-latest

    steps:
      - name: cancel old workflow
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: set IMAGE VERSION
        run: echo "IMAGE_VERSION=$(echo '${{ matrix.images }}' | sed -e 's/debian\///g' -e 's/\//-/g')" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registory
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build And Push
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.images }}/Dockerfile
          platforms: linux/amd64
          tags: |
            fagai/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            ghcr.io/fagai/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          push: ${{ github.ref == 'refs/heads/master' }}
          cache-from: type=registry,ref=fagai/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          cache-to: type=inline

  push-phalcon:
    needs: push
    strategy:
      fail-fast: false
      matrix:
        images:
          - "7.2/alpine/phalcon-fpm"
          - "7.2/debian/phalcon-fpm"
          - "7.3/alpine/phalcon-fpm"
          - "7.3/debian/phalcon-fpm"
          - "7.4/alpine/phalcon4-fpm"
          - "7.4/debian/phalcon4-fpm"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: set IMAGE VERSION
        run: echo "IMAGE_VERSION=$(echo '${{ matrix.images }}' | sed -e 's/debian\///g' -e 's/\//-/g')" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registory
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build And Push
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.images }}/Dockerfile
          platforms: linux/amd64
          tags: |
            fagai/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            ghcr.io/fagai/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          push: ${{ github.ref == 'refs/heads/master' }}
          cache-from: type=registry,ref=fagai/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          cache-to: type=inline
